services:

  openplc:
    build:
      context: software/OpenPLC
      dockerfile: Dockerfile
    restart: always
    privileged: true
    ports:
      - 8080:8080
      - 502:502

  # opcua:
  #   build:
  #     context: software/opcua
  #     dockerfile: Dockerfile
  #   restart: always
  #   depends_on:
  #   - openplc

  # fuxa:
  #   build:
  #     context: software/FUXA
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 1881:1881
  #   depends_on:
  #   - openplc

  hwio:
    build:
      context: software/hwio-virtual
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:8090
    depends_on:
    - openplc
