services:
  # Der Router, den wir testen wollen
  router-test:
    image: cybics-openwrt-router:test
    build:
      context: .
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "2222:2222"
    networks:
      test_ext:
        ipv4_address: 172.19.0.2
      test_int:
        ipv4_address: 172.18.0.254

  # Ein Test-Client im "Internet" (WAN)
  wan-probe:
    image: alpine
    command: sh -c "ip route add 172.18.0.0/24 via 172.19.0.2 && sleep infinity"
    cap_add:
      - NET_ADMIN 
    networks:
      test_ext:
        ipv4_address: 172.19.0.100
    depends_on:
      - router-test

  # Ein Test-Server im "ICS-Netz" (LAN)
  lan-probe:
    image: alpine
    command: sleep infinity
    networks:
      test_int:
        ipv4_address: 172.18.0.10
    depends_on:
      - router-test

networks:
  test_ext:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
  test_int:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24