version: "3.4"
services:
  attack:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../../.dev.env
      - ../../.env
    volumes:
      - ../../:/CybICS
      - ~/.gitconfig:/home/docker/.gitconfig
      - $DOCKER_ENV_DIR/.bash_history:/home/docker/.bash_history
    user: ${HOST_UID:-1000}:${HOST_UID:-1000}

  openplc:
    build:
      context: ../../software/OpenPLC
      dockerfile: Dockerfile
    restart: always
    privileged: true
    ports:
      - 8080:8080

  opcua:
    build:
      context: ../../software/opcua
      dockerfile: Dockerfile
    restart: always
    depends_on:
    - openplc

  fuxa:
    build:
      context: ../../software/FUXA
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1881:1881
    depends_on:
    - openplc
