title: CybICS
description: Cyber-Physical Industrial Control System
baseurl: "/CybICS"
url: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
minima:
  skin: dark
  header_pages:
    - index.md
    - docs.md
    - about.md

# Social links
github_username: mniedermaier
repository: mniedermaier/CybICS

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 