---
# Site settings
title: CybICS
subtitle: Cybersecurity Testbed for Industrial Control Systems
description: Cybersecurity Testbed for Industrial Control Systems
baseurl: "/CybICS"
url: "https://mniedermaier.github.io/CybICS"

# Theme settings
remote_theme: longpdo/neumorphism

# Landing page
username: CybICS
typing_text: Cybersecurity Testbed for Industrial Control Systems
email:
github_username: mniedermaier
linkedin_username: matthias-niedermaier

# About section
show_about_card: true
about_title: About CybICS
about_description: CybICS is a fully open-source platform for simulating cyber-physical systems, designed to study cyberattacks and countermeasures in industrial control systems (ICS). It provides a full virtual environment using Docker Compose and also supports integration with real hardware setups, enabling realistic and flexible testing scenarios for research and education.

# Choose section
show_choose_card: true
choose_title: Choose a Side

# Skills section
show_skills_card: true
skills_title: Features

# Timeline section
show_timeline_card: true
timeline_title: Development Timeline

# Projects section
show_projects_card: true

# Contact section
show_contact_card: true
contact_title: Contact
contact_description: Get in touch with us to learn more about CybICS and how it can help secure your infrastructure.

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - .github
  - README.md
  - LICENSE
  - .git
  - .vscode
  - .idea
  - .DS_Store
  - Thumbs.db

# Navigation
header_pages:
  - index.html

# Repository settings
repository: mniedermaier/CybICS

# Permalinks
permalink: /:title/
--- 