---
# Site settings
title: CybICS
description: Cyber Infrastructure Control System - A comprehensive solution for managing and monitoring cyber infrastructure
baseurl: "/CybICS"
url: "https://mniedermaier.github.io"

# Theme settings
remote_theme: longpdo/neumorphism

# Social media
github_username: mniedermaier
linkedin_username: mniedermaier

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - .github
  - README.md
  - LICENSE
  - .git
  - .vscode
  - .idea
  - .DS_Store
  - Thumbs.db

# Navigation
header_pages:
  - index.md
  - docs.md
  - about.md
--- 