title: CybICS
description: Cyber-Physical Industrial Control System
baseurl: "/CybICS"
url: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
minima:
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
    github: mniedermaier/CybICS

# Site settings
show_excerpts: false

# Colors and theme
colors:
  background: "#0d1117"
  darker_bg: "#010409"
  accent: "#00ff00"
  accent_dark: "#00cc00"
  text: "#e6e6e6"
  text_muted: "#8b949e"

# Navigation
header_pages:
  - index.md
  - docs.md
  - about.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 