remote_theme: longpdo/neumorphism
title: CybICS
description: >-
  CybICS - Cyber Infrastructure Control System
  A comprehensive solution for managing and monitoring cyber infrastructure
baseurl: ""
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - .github
  - README.md
  - LICENSE
  - .git
  - .vscode
  - .idea
  - .DS_Store
  - Thumbs.db

# Site settings
show_excerpts: false

# Navigation
header_pages:
  - index.md
  - docs.md
  - about.md 